### ISSUE TITLE
[frontend] allow token import in `/manage`

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#45]
Users should be able to import token addresses in the `/manage` page. The import should fail if the connected wallet is not the owner, otherwise the token address can be added to the zustand slice described in #42

**Comment by givingmittal** [comment]
@0xChqrles I can take this up

**Comment by mananbordia** [comment]
@abdelhamidbakhta @0xChqrles I want to pick this task and complete this EOW.
I'm new to the web3 ecosystem and would need some help in understanding how import of token works.

What persona is expected to import this token (from description it seems like token owner will import) ?
What happens when token is imported ?
Can you please refer some other projects which have similar product ?
